name: Laravel Tests

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Ensure .env.testing exists
        run: cp .env.testing .env || touch .env

      - name: Generate key
        run: php artisan key:generate --force

      - name: Run Migrations
        run: php artisan migrate --env=testing --force

      - name: Run Tests
        run: php artisan test
